repo: src/v8
patches:
-
  owners: alespergl
  file: build_gn.patch
  description: null
-
  owners: zcbenz
  file: array_buffer.patch
  description: null
-
  owners: zcbenz
  file: mksnapshot.patch
  description: null
-
  owners: zcbenz
  file: ostreams.patch
  description: null
-
  owners: alexeykuzmin
  file: export_platform.patch
  description: null
-
  owners: alespergl
  file: dcheck.patch
  description: null
